apiVersion: v1
kind: Pod
metadata:
  name: nginx-stress
spec:
  containers:
  - name: nginx
    image: ubuntu/nginx
    ports:
    - containerPort: 80
  - name: stress
    image: progrium/stress
    command: ["sudo", "stress", "--cpu", "4", "-v", "--timeout", "3000s"]
